version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - '3000:1337'
    volumes: 
      - /app/node_modules
      - .:/app
    environment: 
      - PORT=1337
  redis-server:
    image: 'redis'